#!/bin/bash

echo "🚀 Healthcare UX Dashboard - GitHub Deployment"
echo "=============================================="
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Create the repository on GitHub:"
echo "   → Go to: https://github.com/new"
echo "   → Repository name: healthcare-ux-dashboard"
echo "   → Make it PUBLIC (for free GitHub Pages)"
echo "   → DO NOT add README (we have one)"
echo "   → Click 'Create repository'"
echo ""
echo "2. Then run this command to push:"
echo "   git push -u origin main"
echo ""
echo "3. Enable GitHub Pages:"
echo "   → Go to: https://github.com/Anika-007/healthcare-ux-dashboard/settings/pages"
echo "   → Source: GitHub Actions"
echo ""
echo "4. Your live URL will be:"
echo "   https://anika-007.github.io/healthcare-ux-dashboard/"
echo ""
echo "=============================================="
echo ""
echo "✅ Git repository is initialized and ready!"
echo "✅ All files are committed!"
echo "✅ Remote is set to: https://github.com/Anika-007/healthcare-ux-dashboard.git"
echo ""
echo "Just create the repo on GitHub and push! 🎉"
